### PR TITLE
Added Logo and title name

### PR DESCRIPTION
**Pull request by linga66**
As mentioned in the issue id #119 

Screenshot (693)

### CODE REVIEW

**Comment by linga66** [comment]
@ak736 do check this

**Comment by ak736** [comment]
Can you make it responsive as well?

**Comment by linga66** [comment]
> Can you make it responsive as well?

Completed @ak736

**Comment by linga66** [comment]
Do check it @ak736

**Comment by linga66** [comment]
@ak736 do review!

**Comment by linga66** [comment]
@ak736 review it!

**Pull request closed without merging**
