### PR TITLE
Fixing 404 Error on Refreshing Website Route

### PR DESCRIPTION
**Pull request by Nishitbaria**
This pull request addresses the issue regarding the 404 error that occurs when refreshing the website route "https://the-project-marketplace.vercel.app/dashboard". The problem has been resolved, and the Dashboard page now loads successfully without any errors, even after refreshing the page.

*Changes Made:*
- Reviewed the routing configuration and server settings to identify the cause of the 404 error.
- Updated the routing logic to handle the Dashboard route properly and prevent the occurrence of a 404 error.
- Tested the changes thoroughly to ensure that the Dashboard page functions correctly and remains accessible on refreshing.

*Testing Done:*
- Manually tested the refreshed route "https://the-project-marketplace.vercel.app/dashboard" on the deployed website.
- Verified that the Dashboard page loads without encountering a 404 error after refreshing.
- Checked for any unexpected side effects or regressions in other parts of the website, and confirmed that all other functionality remains intact.

I believe these changes effectively address the 404 error issue on refreshing the website route. Please review and merge this pull request to incorporate the fixes. Thank you!

### CODE REVIEW

**Comment by ak736** [comment]
Unable to see your preview

**Comment by Nishitbaria** [comment]
here is My Deploy Link : https://project-marketplace-2ve5b9v16-nishitbaria.vercel.app/ 
which has solve this problem

**Comment by ak736** [comment]
Great work

**Comment by Nishitbaria** [comment]
Hey @ak736  You haven't added till Level 2 and gssoc  label tag please add it

**Pull request merged**
