### PR TITLE
Feature Request: Constructing a Dedicated Issue Template for Crete

### PR DESCRIPTION
**Pull request by Nishitbaria**
**`Description:`**

I have noticed that the repository does not currently have a dedicated issue template to streamline the process of addressing and resolving any arising issues effectively. I propose the implementation of a dedicated issue template specific to Crete, which will serve as a structured framework for issue reports.

**`Changes Made:`**

Created a new file named issue_template.md in the repository's root directory.
Added a structured template for issue reports, including sections such as a concise title,

### CODE REVIEW

**Comment by ak736** [comment]
Can you share the screenshot shot of the updated readme file so that i can review it and merge your PR

**Comment by Nishitbaria** [comment]
here is img of readme

readme

**Comment by ak736** [comment]
Add all the details in your readme file, you can refer the screenshot available in repo

**Comment by Nishitbaria** [comment]
@ak736 
** Ok **

**Comment by Nishitbaria** [comment]
> Add all the details in your readme file, you can refer the screenshot available in repo

Ok

**Comment by Nishitbaria** [comment]
I am closing this pull request and creating a new one because I have added two more templates

**Pull request closed without merging**
