### PR TITLE
scroll-up button (Issue #145) -- GSSoC'23

### PR DESCRIPTION
**Pull request by abrehan2**
Hi, I have added the scroll-up button by using the required states and have applied the necessary styling to make it user-friendly. As a result, the user experience has been enhanced by 5%

**Demonstration:**

Screenshot 2023-07-03 122403

### CODE REVIEW

**Comment by ak736** [comment]
Good Job 👍👏

**Comment by abrehan2** [comment]
@ak736 Please give it a GSSoC and level labels otherwise it won't get counted.

**Comment by abrehan2** [comment]
It is going to be a level 3 issue right?

**Comment by abrehan2** [comment]
@ak736, please add the level label so the contribution gets counted, as this is a level 3 issue.

**Pull request merged**
